services:
  - type: web
    name: galand
    env: node
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    publishPath: dist
    envVars:
      - key: SIMPLE_CASHIER_BASE_URL
        sync: false
      - key: PUBLIC_NEON_AUTH_URL
        sync: false
